### ISSUE TITLE
White screen in notification view in iOS

### ISSUE THREAD

**Issue by kaystd** [exponea/exponea-react-native-sdk#10]
Hello!
In iOS 14.3 if I don't attach an image url, white screen will be displayed

**Comment by wassil** [comment]
Hi, thank you for the report! We'll look into this. Most probably an issue in the underlying native Exponea iOS SDK

**Comment by ivan-latka-exponea** [comment]
I will just add that as far as we know problem was reproduced only in react native SDK, but we are still investigating iOS SDK.
Problem was reproduced in both iOS 14.3 and 14.4 and the fix (at least for reack native SDK) should be release hopefully next week.

**Comment by Kaso1212** [comment]
Hello,
At our client we have this issue in **exponea-ios-sdk** 
Do you working on this issue also for this SDK ?

**Comment by Igi4** [comment]
Hi :)

Thanks for the report!

Firstly, this is not an issue with the Exponea React Native or iOS SDK, iOS nor anything else. It’s a setting in `info.plist` file for the Notification Content Extension. Please notice the parameter underlined with purple line on the attached screenshot below. The screenshot is taken from our documentation on how to integrated rich push notifications on iOS (https://github.com/exponea/exponea-ios-sdk/blob/develop/Documentation/Guide/PUSH_QUICKSTART.md#notification-content-extension).

<img width="1084" alt="Screenshot 2021-02-10 at 14 52 58" src="https://user-images.githubusercontent.com/1747133/107523471-0ad64800-6bb5-11eb-81f8-e5e2c0a83571.png">

The parameter is called `UNNotificationExtensionInitialContentSizeRatio` and its default value is 1, which means, that the ratio between the width and the height of the content in the push notification is 1 (basically the content is as high as it’s wide).

If you set this value to 0, it will achieve what you need. The area for the content of the push notification will initially have full width but zero height and it will grow to needed height if there is an image present or it will remain zero if there is no image. Please note that this is applied only to the area where the image resides. It makes no difference for the text part at the bottom of the notification.

We will update our documentation and mention this behaviour in it so that it's clear how it works. Please let me know if you have more questions or even it it worked for you :)

**Comment by kaystd** [comment]
It's working. Thanks!
