### ISSUE TITLE
Customer property "google_push_notification_id" is missing

### ISSUE THREAD

**Issue by mustymustafa10** [exponea/exponea-react-native-sdk#52]
I am trying to send a test notification to android devices through the exponea web interface, but i keep getting the following error: 
Customer property "google_push_notification_id" is missing.

Version: react-native-exponea-sdk@1.0.0

**Comment by michaela-dev** [comment]
This error occurs when the firebase token is not tracked to the Exponea. When you updated to version 1.0.0, did you follow the version update guide? https://github.com/exponea/exponea-react-native-sdk/blob/master/documentation/VERSION_UPDATE.md ?

FirebaseMessagingService is not a part of SDK anymore, and it should be created on the app side for push notifications to keep working.

**Comment by coyksdev** [comment]
Hi, @michaela-dev. I have a similar issue.  Whenever I am trying to test notification it shows Customer property "google_push_notification_id" is missing.

**Comment by adam1929** [comment]
Hi @coyksdev do you add SDK into existing app? Do you have Firebase in your app previously?
There is some token-update behaviour mentioned here https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdService.html#onTokenRefresh()
that you do not get new token if app just updates.

**Comment by petgus-lyko** [comment]
Check that the Exponea authorizationToken you are using has permission to create new properties for your customers in Exponea. 
If "google_push_notification_id" is not already a property for customers this can be an issue.

You will probably see an error about this if you enable more verbose logging.
`Exponea.setLogLevel(LogLevel.VERBOSE)`

<img width="1290" alt="Screenshot 2022-09-12 at 17 07 25" src="https://user-images.githubusercontent.com/84783359/189690534-f4bec923-53d2-4171-835d-6d58e72042ab.png">

An alternative solution would be to manually create the property "google_push_notification_id" as an admin instead of letting the SDK to it for you.

**Comment by coyksdev** [comment]
@adam1929 @petgus-lyko Sorry already figured it out. Thank you!
