### ISSUE TITLE
Peer dependency resolve error

### ISSUE THREAD

**Issue by frenic** [exponea/exponea-react-native-sdk#65]
I have `react-native@0.67.3` installed and receive the following error when installing. Everything works fine locally with `npm install --force`. A revision on your peer dependency should be relevant given that `react-native@0.70` was released recently. Thank you!

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-native-exponea-sdk@1.0.0
npm ERR! Found: react-native@0.67.3
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.3" from the root project
npm ERR!   peer react-native@"^0.0.0-0 || 0.60 - 0.67 || 1000.0.0" from @react-native-async-storage/async-storage@1.16.1
npm ERR!   node_modules/@react-native-async-storage/async-storage
npm ERR!     @react-native-async-storage/async-storage@"^1.16.1" from the root project
npm ERR!     @react-native-async-storage/async-storage@"^1.13.4" from raygun4reactnative@1.2.2
npm ERR!     node_modules/raygun4reactnative
npm ERR!       raygun4reactnative@"^1.2.2" from the root project
npm ERR!   31 more (@react-native-community/cli, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"<=0.67.0" from react-native-exponea-sdk@1.0.0
npm ERR! node_modules/react-native-exponea-sdk
npm ERR!   react-native-exponea-sdk@"^1.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react-native@0.67.0
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"<=0.67.0" from react-native-exponea-sdk@1.0.0
npm ERR!   node_modules/react-native-exponea-sdk
npm ERR!     react-native-exponea-sdk@"^1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by adam1929** [comment]
Thank you for your comment.
Yes, we done "version freeze" on multiple libs and framework due to unstable auto-update versioning.
Thanks for clarification that latest RN version is buildable for out SDK, but please keep in mind that it may be unstable and may be throwing runtime exceptions or invalid behaviour (I hope for no problems at all)
There is a plan to update all resources to latest and stable versions, that needs a time to revalidate all functionalities. I'm afraid that I'm not able to give you a more precise release date of next update, should be in couple of weeks

**Comment by frenic** [comment]
Thank you for your response. But to clarify: I haven't built the package with latest React Native 0.70. Only for version 0.67.3, which seems to work fine.

**Comment by petgus-lyko** [comment]
Can you give us an update on this @adam1929?
Peer dependency is still `"react-native": "<=0.67.0"`
React Native is now at `0.70.5`

**Comment by adam1929** [comment]
Hi, we have in plans to upgrade/support latest RN, it may occur in next release. But I'm not able to tell specific release date

**Comment by frenic** [comment]
@adam1929 It "may occur" and "not able to tell specific date"? If Exponea would be a free open source service, I would respect that answer. But it's **not** a free open source service. I understand that you have many packages to maintain. But a technical dept like this is outrageous. React Native 0.67 is not even supported anymore. So I would kindly ask you to get back to us with a better answer than that. Thank you!

**Comment by xcibik00** [comment]
Hi @frenic,

Thank you for raising this issue - we register this technical debt and aim to update all resources to the latest and stable versions. For now, release frequency for Exponea SDK wrappers is not as often as for native SDKs (iOS/Android) - usually just a few times a year more like batch updates. We fully understand your situation - we want to mention that the GitHub issue is not an official way to contact Exponea support ([How to contact Exponea Support](https://documentation.bloomreach.com/engagement/docs/engagement-support#contacting-the-support)). For this specific case we already moved this issue to official support - can you please just reach them out to verify and pair this issue with customer (you can use this GitHub issue link in email)?, also for the future, if you are an Exponea customer, please contact support directly instead of creating a GitHub issue.

Regarding the issue, as is - we will reconsider the timeline and delivery of RN update in Exponea RN SDK during our Tuesday planning meeting. We will let you know right after with more specific information.

Thanks and Regards.
Have a nice day.
Peter

**Comment by frenic** [comment]
Thank you for your answer! I will consider contacting support next time.
