### ISSUE TITLE
Support for react-native 0.71.3

### ISSUE THREAD

**Issue by LouisRaine** [exponea/exponea-react-native-sdk#83]
Heya when will support for newest react native be available?

**Comment by thuongtv-vn** [comment]
Hi @LouisRaine 
I am facing the build error with react native version 0.6.35. Does it support on this version?

**Comment by xcibik00** [comment]
Hi @LouisRaine and @thuongtv-vn ,

Regarding the first question @LouisRaine - we are currently working on new Exponea React Native SDK version which should  also contains support of newest RN version - 0.71.x. Should be available soon this month.

The second one @thuongtv-vn - we are supporting the widest possible spectrum of versions, so yes, it should be supported, but since it is a fairly old version - there may be some incompatibility. Please send us more information about errors/crashes and we will look into it, but we definitely recommend updating the RN version to a higher one

Regards

**Comment by thuongtv-vn** [comment]
Hi @xcibik00 

I already open an issue for error detail:
https://github.com/exponea/exponea-react-native-sdk/issues/84

Could you please help me to check

Thanks so much!
