### ISSUE TITLE
iOS crash with EXC_BREAKPOINT (SIGTRAP)

### ISSUE THREAD

**Issue by ViktorOsadchyi** [exponea/exponea-react-native-sdk#85]
We are facing crashes on production on IOS.
The issue appears on App start

<img width="911" alt="Screenshot 2023-05-31 at 15 53 19" src="https://github.com/exponea/exponea-react-native-sdk/assets/24491018/7c03bc17-7453-4186-9e45-a368493403bc">

<img width="773" alt="Screenshot 2023-05-31 at 15 55 32" src="https://github.com/exponea/exponea-react-native-sdk/assets/24491018/a460b8ee-9892-4f71-a2b0-68941c455596">

According to the logs, a crash occurs in the TrackingManager file when the notification manager is called, that the application has become active.

Additional info:

"react-native-exponea-sdk": "1.4.0"
"react-native": "0.70.6"

**Comment by adam1929** [comment]
Hi @ViktorOsadchyi thank you for your findings.
This error was known for ReactNative SDK 1.2.0, where iOS SDK 2.13.1 has been used. Issue occurs due to accessing of internal code too soon (issue on SDK side, not in app). And has been fixed iOS 2.15.0, so in ReactNative SDK 1.3.0.
Please ensure, that you are using newer SDK. You wrote that you should using 1.4.0 RN SDK, but stacktrace lines  (TrackingManager.swift:343), (TrackingManager.swift:343) and others do match with iOS 2.13.1 perfectly.

**Comment by ViktorOsadchyi** [comment]
@adam1929  thanks, we already updated ReactNative SDK to 1.4.0 and I don't see this error anymore in the new version
