### ISSUE TITLE
Manifest merger failed - Attribute application@fullBackupContent value=(false) from AndroidManifest.xml

### ISSUE THREAD

**Issue by phuongwd** [exponea/exponea-react-native-sdk#92]
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Attribute application@fullBackupContent value=(false) from AndroidManifest.xml:22:9-42
  	is also present at [com.exponea.sdk:sdk:3.6.1] AndroidManifest.xml:14:9-70 value=(@xml/exponea_default_backup_rules).
  	Suggestion: add 'tools:replace="android:fullBackupContent"' to <application> element at AndroidManifest.xml:5:2-11:19 to override.
```

I found this guide https://github.com/AppsFlyerSDK/appsflyer-android-sdk/issues/9#issuecomment-760150089 but unsure its correct on latest on version?

Please advise, thank you!

**Comment by thuongtv-vn** [comment]
Im facing the same issue.

**Comment by adam1929** [comment]
Hi @phuongwd @thuongtv-vn thank you for reporting.
Yes, provide such a solution you found.
As you can read in solution, issue is caused by SDK's auto-backup feature and yours. Please try to include a rules from SDKs `exponea_default_backup_rules` within yours.
If you replace backup rules without including from SDK, nothing bad will happen.
